-- LinguaLoop V1 schema
-- Catalogue: language -> unit -> lesson -> exercise
-- Learner domain: learner, review_state, session, attempt, streak
-- Audio: audio_asset (referenced by LISTEN exercises)

CREATE TYPE exercise_type AS ENUM ('TRANSLATE', 'MULTIPLE_CHOICE', 'LISTEN');

CREATE TABLE language (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE unit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_id BIGINT       NOT NULL REFERENCES language (id) ON DELETE CASCADE,
    title       VARCHAR(200) NOT NULL,
    position    INT          NOT NULL,
    CONSTRAINT uq_unit_language_position UNIQUE (language_id, position)
);

CREATE TABLE lesson (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id  BIGINT       NOT NULL REFERENCES unit (id) ON DELETE CASCADE,
    title    VARCHAR(200) NOT NULL,
    position INT          NOT NULL,
    CONSTRAINT uq_lesson_unit_position UNIQUE (unit_id, position)
);

CREATE TABLE audio_asset (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_key   VARCHAR(255) NOT NULL UNIQUE,
    url         VARCHAR(500) NOT NULL,
    mime_type   VARCHAR(100) NOT NULL,
    duration_ms INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE exercise (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id      BIGINT        NOT NULL REFERENCES lesson (id) ON DELETE CASCADE,
    type           exercise_type NOT NULL,
    prompt         TEXT          NOT NULL,
    answer         TEXT          NOT NULL,
    choices        JSONB,
    audio_asset_id BIGINT        REFERENCES audio_asset (id) ON DELETE SET NULL,
    caption        TEXT
);

CREATE TABLE learner (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    display_name  VARCHAR(100) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    timezone      VARCHAR(64)  NOT NULL DEFAULT 'UTC'
);

CREATE TABLE review_state (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learner_id    BIGINT           NOT NULL REFERENCES learner (id) ON DELETE CASCADE,
    exercise_id   BIGINT           NOT NULL REFERENCES exercise (id) ON DELETE CASCADE,
    ease_factor   DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    interval_days DOUBLE PRECISION NOT NULL DEFAULT 0,
    repetitions   INT              NOT NULL DEFAULT 0,
    due_at        TIMESTAMPTZ      NOT NULL,
    last_grade    SMALLINT         CHECK (last_grade IS NULL OR (last_grade BETWEEN 0 AND 5)),
    lapses        INT              NOT NULL DEFAULT 0,
    CONSTRAINT uq_review_state_learner_exercise UNIQUE (learner_id, exercise_id)
);

CREATE TABLE session (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learner_id  BIGINT      NOT NULL REFERENCES learner (id) ON DELETE CASCADE,
    lesson_id   BIGINT      NOT NULL REFERENCES lesson (id) ON DELETE CASCADE,
    started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at    TIMESTAMPTZ,
    variant_key VARCHAR(64)
);

CREATE TABLE attempt (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT    NOT NULL REFERENCES session (id) ON DELETE CASCADE,
    exercise_id BIGINT    NOT NULL REFERENCES exercise (id) ON DELETE CASCADE,
    grade       SMALLINT  NOT NULL CHECK (grade BETWEEN 0 AND 5),
    latency_ms  INT       NOT NULL CHECK (latency_ms >= 0),
    hint_shown  BOOLEAN   NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE streak (
    learner_id       BIGINT PRIMARY KEY REFERENCES learner (id) ON DELETE CASCADE,
    current_days     INT  NOT NULL DEFAULT 0,
    longest_days     INT  NOT NULL DEFAULT 0,
    last_active_date DATE
);

CREATE INDEX idx_unit_language             ON unit (language_id);
CREATE INDEX idx_lesson_unit               ON lesson (unit_id);
CREATE INDEX idx_exercise_lesson           ON exercise (lesson_id);
CREATE INDEX idx_review_state_learner_due  ON review_state (learner_id, due_at);
CREATE INDEX idx_attempt_session           ON attempt (session_id);
CREATE INDEX idx_session_learner           ON session (learner_id);
